kind: pipeline
type: docker
name: keycloak-spi

# Broaden triggers for debugging
trigger:
  event:
    - push
    - custom
  branch:
    - main
    - master

steps:
  - name: debug-info
    image: alpine
    commands:
      - echo "Pipeline triggered by ${DRONE_COMMIT_AUTHOR} on ${DRONE_COMMIT_BRANCH}"
      - ls -R

  - name: build-spi
    image: eclipse-temurin:21-jdk
    # Path filter at step level is safer for debugging
    when:
      path:
        include:
          - "keycloak-spi/**"
          - ".drone.yml"
    commands:
      - ./gradlew :keycloak-spi:shadowJar --no-daemon
      - cp keycloak-spi/build/libs/keycloak-user-storage-spi-*.jar /shared/providers/keycloak-user-storage-spi.jar
    volumes:
      - name: providers
        path: /shared/providers

volumes:
  - name: providers
    host:
      path: /opt/keycloak-providers

---
kind: pipeline
type: docker
name: keycloak-spi-release

trigger:
  event:
    - tag

steps:
  - name: release-build
    image: eclipse-temurin:21-jdk
    commands:
      - ./gradlew :keycloak-spi:shadowJar --no-daemon