kind: pipeline
type: docker
name: keycloak-spi

trigger:
  event: [push, custom]

steps:
  - name: verify-environment
    image: alpine
    commands:
      - uname -m
      - echo "Runner is working!"

  - name: build-test
    image: eclipse-temurin:21-jdk
    commands:
      - ./gradlew --version