/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/realms/': RouteRecordInfo<
      '/realms/',
      '/realms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/realms/[name]/': RouteRecordInfo<
      '/realms/[name]/',
      '/realms/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/realms/[name]/clients/': RouteRecordInfo<
      '/realms/[name]/clients/',
      '/realms/:name/clients',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/realms/[name]/clients/[clientId]/': RouteRecordInfo<
      '/realms/[name]/clients/[clientId]/',
      '/realms/:name/clients/:clientId',
      { name: ParamValue<true>, clientId: ParamValue<true> },
      { name: ParamValue<false>, clientId: ParamValue<false> },
      | never
    >,
    '/realms/[name]/clients/create': RouteRecordInfo<
      '/realms/[name]/clients/create',
      '/realms/:name/clients/create',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/realms/[name]/groups/': RouteRecordInfo<
      '/realms/[name]/groups/',
      '/realms/:name/groups',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/realms/[name]/groups/create': RouteRecordInfo<
      '/realms/[name]/groups/create',
      '/realms/:name/groups/create',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/realms/[name]/idp/': RouteRecordInfo<
      '/realms/[name]/idp/',
      '/realms/:name/idp',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/realms/[name]/idp/create': RouteRecordInfo<
      '/realms/[name]/idp/create',
      '/realms/:name/idp/create',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/realms/[name]/roles/': RouteRecordInfo<
      '/realms/[name]/roles/',
      '/realms/:name/roles',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/realms/[name]/roles/create': RouteRecordInfo<
      '/realms/[name]/roles/create',
      '/realms/:name/roles/create',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/realms/create': RouteRecordInfo<
      '/realms/create',
      '/realms/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/realms/index.vue': {
      routes:
        | '/realms/'
      views:
        | never
    }
    'src/pages/realms/[name]/index.vue': {
      routes:
        | '/realms/[name]/'
      views:
        | never
    }
    'src/pages/realms/[name]/clients/index.vue': {
      routes:
        | '/realms/[name]/clients/'
      views:
        | never
    }
    'src/pages/realms/[name]/clients/[clientId]/index.vue': {
      routes:
        | '/realms/[name]/clients/[clientId]/'
      views:
        | never
    }
    'src/pages/realms/[name]/clients/create.vue': {
      routes:
        | '/realms/[name]/clients/create'
      views:
        | never
    }
    'src/pages/realms/[name]/groups/index.vue': {
      routes:
        | '/realms/[name]/groups/'
      views:
        | never
    }
    'src/pages/realms/[name]/groups/create.vue': {
      routes:
        | '/realms/[name]/groups/create'
      views:
        | never
    }
    'src/pages/realms/[name]/idp/index.vue': {
      routes:
        | '/realms/[name]/idp/'
      views:
        | never
    }
    'src/pages/realms/[name]/idp/create.vue': {
      routes:
        | '/realms/[name]/idp/create'
      views:
        | never
    }
    'src/pages/realms/[name]/roles/index.vue': {
      routes:
        | '/realms/[name]/roles/'
      views:
        | never
    }
    'src/pages/realms/[name]/roles/create.vue': {
      routes:
        | '/realms/[name]/roles/create'
      views:
        | never
    }
    'src/pages/realms/create.vue': {
      routes:
        | '/realms/create'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
