# Auth Backend - Release with Docker Compose Deployment
# Triggered automatically when a tag v* is created
when:
  - event: tag
    ref: refs/tags/v*

steps:
  - name: build-and-push
    image: amazoncorretto:21
    volumes:
      - /var/lib/woodpecker/cache/gradle:/root/.gradle
    environment:
      CI: "true"
      GRADLE_OPTS: "-Xmx128m"
      GITHUB_TOKEN:
        from_secret: github_token
      S3_BUILD_CACHE_BUCKET:
        from_secret: s3_build_cache_bucket
      S3_BUILD_CACHE_REGION:
        from_secret: s3_build_cache_region
      AWS_ACCESS_KEY_ID:
        from_secret: s3_build_cache_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: s3_build_cache_secret_key
      S3_BUILD_CACHE_ENDPOINT:
        from_secret: s3_build_cache_endpoint
    commands:
      - rm -rf /root/.gradle/daemon 2>/dev/null || true
      - find /root/.gradle -name "*.lock" -type f -delete 2>/dev/null || true
      - |
        VERSION=${CI_COMMIT_TAG#v}
        echo "Building and pushing Auth Backend version $VERSION"
        ./gradlew :bootJar :jib --no-daemon -x test -PjibTag=$VERSION -Djib.to.auth.username=dsjkeeplearning -Djib.to.auth.password=$GITHUB_TOKEN
        # Also tag as latest
        ./gradlew :jib --no-daemon -x test -PjibTag=latest -Djib.to.auth.username=dsjkeeplearning -Djib.to.auth.password=$GITHUB_TOKEN
        mkdir -p release-assets
        cp build/libs/*.jar release-assets/

  - name: github-release
    image: alpine
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - apk add --no-cache github-cli git
      - |
        VERSION=${CI_COMMIT_TAG}
        PREV_TAG=$(git tag -l 'v*' --sort=-v:refname | grep -v 'spi-v' | grep -v 'release-v' | grep -v $VERSION | head -n1)
        if [ -z "$PREV_TAG" ]; then
          PREV_TAG=$(git rev-list --max-parents=0 HEAD)
        fi

        echo "# Changelog for $VERSION" > release-assets/CHANGELOG.md
        echo "" >> release-assets/CHANGELOG.md
        git log $PREV_TAG..HEAD --pretty=format:"- %s (%h)" -- src/ build.gradle.kts >> release-assets/CHANGELOG.md || echo "- No changes" >> release-assets/CHANGELOG.md

        if gh release view $CI_COMMIT_TAG --repo $CI_REPO > /dev/null 2>&1; then
          gh release edit $CI_COMMIT_TAG --repo $CI_REPO --notes-file release-assets/CHANGELOG.md
          gh release upload $CI_COMMIT_TAG --repo $CI_REPO --clobber release-assets/*
        else
          gh release create $CI_COMMIT_TAG \
            --repo $CI_REPO \
            --title "Auth Backend $CI_COMMIT_TAG" \
            --notes-file release-assets/CHANGELOG.md \
            release-assets/*
        fi

  - name: deploy-with-compose
    image: docker:cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
      # Environment variables for docker-compose
      DB_HOST:
        from_secret: db_host
      DB_PORT:
        from_secret: db_port
      DB_NAME:
        from_secret: db_name
      DB_USERNAME:
        from_secret: db_username
      DB_PASSWORD:
        from_secret: db_password
      KEYCLOAK_BASE_URL:
        from_secret: keycloak_base_url
      KEYCLOAK_ISSUER_PREFIX:
        from_secret: keycloak_issuer_prefix
      KEYCLOAK_SAAS_ISSUER_URI:
        from_secret: keycloak_saas_issuer_uri
      KEYCLOAK_ADMIN_CLIENT_ID:
        from_secret: keycloak_admin_client_id
      KEYCLOAK_ADMIN_CLIENT_SECRET:
        from_secret: keycloak_admin_client_secret
      SAAS_ADMIN_CLIENT_SECRET:
        from_secret: saas_admin_client_secret
      SPRING_PROFILES_ACTIVE:
        from_secret: spring_profiles_active
    commands:
      - apk add --no-cache docker-compose
      - echo $GITHUB_TOKEN | docker login ghcr.io -u dsjkeeplearning --password-stdin
      - |
        # Create .env file from secrets
        cat > .env <<EOF
        DB_HOST=$DB_HOST
        DB_PORT=$DB_PORT
        DB_NAME=$DB_NAME
        DB_USERNAME=$DB_USERNAME
        DB_PASSWORD=$DB_PASSWORD
        KEYCLOAK_BASE_URL=$KEYCLOAK_BASE_URL
        KEYCLOAK_ISSUER_PREFIX=$KEYCLOAK_ISSUER_PREFIX
        KEYCLOAK_SAAS_ISSUER_URI=$KEYCLOAK_SAAS_ISSUER_URI
        KEYCLOAK_ADMIN_CLIENT_ID=$KEYCLOAK_ADMIN_CLIENT_ID
        KEYCLOAK_ADMIN_CLIENT_SECRET=$KEYCLOAK_ADMIN_CLIENT_SECRET
        SAAS_ADMIN_CLIENT_SECRET=$SAAS_ADMIN_CLIENT_SECRET
        SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
        EOF

        echo "Pulling latest images..."
        docker-compose pull

        echo "Deploying with docker-compose..."
        docker-compose up -d --remove-orphans

        echo "Cleaning up old images..."
        docker image prune -f

        echo "Deployment complete!"
        docker-compose ps
        docker logs auth-backend --tail 20
