# Auth Backend - Release (Tag: v*)
# Triggered automatically when ready-release-go creates a tag after release PR merge
when:
  - event: tag
    ref: refs/tags/v*

steps:
  - name: build
    image: eclipse-temurin:21-jdk
    volumes:
      - /var/lib/woodpecker/cache/gradle:/root/.gradle
    environment:
      CI: "true"
      S3_BUILD_CACHE_BUCKET:
        from_secret: s3_build_cache_bucket
      S3_BUILD_CACHE_REGION:
        from_secret: s3_build_cache_region
      AWS_ACCESS_KEY_ID:
        from_secret: s3_build_cache_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: s3_build_cache_secret_key
      S3_BUILD_CACHE_ENDPOINT:
        from_secret: s3_build_cache_endpoint
    commands:
      - find /root/.gradle -name "*.lock" -type f -delete 2>/dev/null || true
      - VERSION=${CI_COMMIT_TAG#v}
      - echo "Building Auth Backend version $VERSION"
      - ./gradlew bootJar -Pversion=$VERSION --no-daemon -x test
      - mkdir -p release-assets
      - cp build/libs/*.jar release-assets/

  - name: generate-changelog
    image: alpine/git
    commands:
      - |
        VERSION=${CI_COMMIT_TAG}
        PREV_TAG=$(git tag -l 'v*' --sort=-v:refname | grep -v 'spi-v' | grep -v 'release-v' | grep -v $VERSION | head -n1)
        if [ -z "$PREV_TAG" ]; then
          PREV_TAG=$(git rev-list --max-parents=0 HEAD)
        fi
        echo "Generating changelog from $PREV_TAG to $VERSION"

        echo "# Changelog for $VERSION" > release-assets/CHANGELOG.md
        echo "" >> release-assets/CHANGELOG.md

        echo "## Auth Backend Changes" >> release-assets/CHANGELOG.md
        git log $PREV_TAG..HEAD --pretty=format:"- %s (%h)" -- src/ build.gradle.kts >> release-assets/CHANGELOG.md || echo "- No changes" >> release-assets/CHANGELOG.md
        echo "" >> release-assets/CHANGELOG.md
        echo "" >> release-assets/CHANGELOG.md

        echo "## Keycloak SPI Changes" >> release-assets/CHANGELOG.md
        git log $PREV_TAG..HEAD --pretty=format:"- %s (%h)" -- keycloak-spi/ >> release-assets/CHANGELOG.md || echo "- No changes" >> release-assets/CHANGELOG.md
        echo "" >> release-assets/CHANGELOG.md
        echo "" >> release-assets/CHANGELOG.md

        echo "## Other Changes" >> release-assets/CHANGELOG.md
        git log $PREV_TAG..HEAD --pretty=format:"- %s (%h)" -- . ':!keycloak-spi/' ':!src/' >> release-assets/CHANGELOG.md || echo "- No changes" >> release-assets/CHANGELOG.md
        echo "" >> release-assets/CHANGELOG.md

        cat release-assets/CHANGELOG.md

  - name: update-readme
    image: alpine/git
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - git config --global user.email "ci@keeplearningos.com"
      - git config --global user.name "Woodpecker CI"
      - git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/${CI_REPO}.git
      - git fetch origin main
      - git checkout main
      - sed -i "s|auth-v[0-9.]*-blue|auth-${CI_COMMIT_TAG}-blue|g" README.md
      - git add README.md
      - git diff --cached --quiet || git commit -m "Update auth version badge to ${CI_COMMIT_TAG}"
      - git push origin main

  - name: github-release
    image: alpine
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - apk add --no-cache github-cli
      - |
        if gh release view $CI_COMMIT_TAG --repo $CI_REPO > /dev/null 2>&1; then
          echo "Release $CI_COMMIT_TAG already exists, updating notes and uploading assets..."
          gh release edit $CI_COMMIT_TAG --repo $CI_REPO --notes-file release-assets/CHANGELOG.md
          gh release upload $CI_COMMIT_TAG --repo $CI_REPO --clobber release-assets/*
        else
          gh release create $CI_COMMIT_TAG \
            --repo $CI_REPO \
            --title "Auth Backend $CI_COMMIT_TAG" \
            --notes-file release-assets/CHANGELOG.md \
            release-assets/*
        fi

  - name: build-and-push-docker
    image: docker:cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - echo $GITHUB_TOKEN | docker login ghcr.io -u dsjkeeplearning --password-stdin
      - VERSION=$CI_COMMIT_TAG
      - echo "Building Docker image with version $VERSION"
      - docker buildx create --name multiarch --driver docker-container --use || docker buildx use multiarch
      - docker buildx build --build-arg VERSION=$VERSION --cache-from type=registry,ref=ghcr.io/dsjkeeplearning/kos-auth-backend:cache --cache-to type=registry,ref=ghcr.io/dsjkeeplearning/kos-auth-backend:cache,mode=max --tag "ghcr.io/dsjkeeplearning/kos-auth-backend:$VERSION" --tag ghcr.io/dsjkeeplearning/kos-auth-backend:latest --push .

  - name: deploy
    image: docker:cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
      KEYCLOAK_ISSUER_PREFIX:
        from_secret: keycloak_issuer_prefix
      KEYCLOAK_SAAS_ISSUER_URI:
        from_secret: keycloak_saas_issuer_uri
      SAAS_ADMIN_CLIENT_SECRET:
        from_secret: saas_admin_client_secret
      DB_HOST:
        from_secret: db_host
      DB_PORT:
        from_secret: db_port
      DB_NAME:
        from_secret: db_name
      DB_USERNAME:
        from_secret: db_username
      DB_PASSWORD:
        from_secret: db_password
      SPRING_PROFILES_ACTIVE:
        from_secret: spring_profiles_active
    commands:
      - VERSION=$CI_COMMIT_TAG
      - echo $GITHUB_TOKEN | docker login ghcr.io -u dsjkeeplearning --password-stdin
      - docker pull "ghcr.io/dsjkeeplearning/kos-auth-backend:$VERSION"
      - docker stop auth-backend || true
      - docker rm auth-backend || true
      - echo "Starting auth-backend with version $VERSION"
      - docker run -d --name auth-backend --restart unless-stopped -p 8080:8080 -e KEYCLOAK_ISSUER_PREFIX="$KEYCLOAK_ISSUER_PREFIX" -e KEYCLOAK_SAAS_ISSUER_URI="$KEYCLOAK_SAAS_ISSUER_URI" -e SAAS_ADMIN_CLIENT_SECRET="$SAAS_ADMIN_CLIENT_SECRET" -e DB_HOST="$DB_HOST" -e DB_PORT="$DB_PORT" -e DB_NAME="$DB_NAME" -e DB_USERNAME="$DB_USERNAME" -e DB_PASSWORD="$DB_PASSWORD" -e SPRING_PROFILES_ACTIVE="$SPRING_PROFILES_ACTIVE" "ghcr.io/dsjkeeplearning/kos-auth-backend:$VERSION"
      - docker image prune -f
