# Keycloak SPI - Build & Test (Push/PR)
when:
  - event: [push, pull_request]
    path:
      include:
        - "keycloak-spi/**"
        - ".woodpecker/keycloak-spi*.yml"
        - "build.gradle.kts"
        - "settings.gradle.kts"

steps:
  - name: build-and-test
    image: eclipse-temurin:21-jdk
    commands:
      - echo "Building and testing Keycloak SPI module..."
      - ./gradlew :keycloak-spi:compileKotlin :keycloak-spi:test :keycloak-spi:shadowJar --no-daemon --build-cache
      - echo "Build successful!"
    volumes:
      - /opt/woodpecker-cache/gradle:/root/.gradle
