# Keycloak SPI - Build & Test (Push/PR/Manual)
when:
  - event: [push, pull_request, manual]
    path:
      include:
        - "keycloak-spi/**"
        - ".woodpecker/keycloak-spi*.yml"
        - "build.gradle.kts"
        - "settings.gradle.kts"

steps:
  - name: restore-cache
    image: meltwater/drone-cache
    volumes:
      - /var/lib/woodpecker/cache:/cache
    settings:
      backend: filesystem
      restore: true
      archive_format: gzip
      filesystem_cache_root: /cache
      cache_key: "gradle-wrapper"
      mount:
        - .gradle

  - name: build-and-test
    image: eclipse-temurin:21-jdk
    environment:
      GRADLE_USER_HOME: .gradle
      CI: "true"
      S3_BUILD_CACHE_BUCKET:
        from_secret: s3_build_cache_bucket
      S3_BUILD_CACHE_REGION:
        from_secret: s3_build_cache_region
      S3_BUILD_CACHE_ACCESS_KEY_ID:
        from_secret: s3_build_cache_access_key_id
      S3_BUILD_CACHE_SECRET_KEY:
        from_secret: s3_build_cache_secret_key
      S3_BUILD_CACHE_ENDPOINT:
        from_secret: s3_build_cache_endpoint
    commands:
      - |
        echo "Verifying S3 cache config..."
        echo "Bucket: $S3_BUILD_CACHE_BUCKET"
        echo "Region: $S3_BUILD_CACHE_REGION"
        echo "Endpoint: $S3_BUILD_CACHE_ENDPOINT"
        echo "Access Key length: ${#S3_BUILD_CACHE_ACCESS_KEY_ID}"
        echo "Secret Key length: ${#S3_BUILD_CACHE_SECRET_KEY}"
      - echo "Building and testing Keycloak SPI module..."
      - ./gradlew :keycloak-spi:compileKotlin :keycloak-spi:test :keycloak-spi:shadowJar --no-daemon
      - echo "Build successful!"

  - name: save-cache
    image: meltwater/drone-cache
    volumes:
      - /var/lib/woodpecker/cache:/cache
    settings:
      backend: filesystem
      rebuild: true
      archive_format: gzip
      filesystem_cache_root: /cache
      cache_key: "gradle-wrapper"
      mount:
        - .gradle
