# Keycloak SPI - Build & Test (Push/PR/Manual)
# Manual trigger: woodpecker-cli pipeline create dsjkeeplearning/kos-auth-backend --branch main --var DEPLOY_TO=keycloak-spi-build
when:
  - event: [push, pull_request]
  - event: manual
    evaluate: 'CI_PIPELINE_DEPLOY_TO == "keycloak-spi-build"'
    path:
      include:
        - "keycloak-spi/**"
        - ".woodpecker/keycloak-spi*.yml"
        - "build.gradle.kts"
        - "settings.gradle.kts"

steps:
  - name: build-and-test
    image: eclipse-temurin:21-jdk
    volumes:
      - /var/lib/woodpecker/cache/gradle:/root/.gradle
    environment:
      CI: "true"
      S3_BUILD_CACHE_BUCKET:
        from_secret: s3_build_cache_bucket
      S3_BUILD_CACHE_REGION:
        from_secret: s3_build_cache_region
      AWS_ACCESS_KEY_ID:
        from_secret: s3_build_cache_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: s3_build_cache_secret_key
      S3_BUILD_CACHE_ENDPOINT:
        from_secret: s3_build_cache_endpoint
    commands:
      - |
        echo "Verifying S3 cache config..."
        echo "Bucket: $S3_BUILD_CACHE_BUCKET"
        echo "Region: $S3_BUILD_CACHE_REGION"
        echo "Endpoint: $S3_BUILD_CACHE_ENDPOINT"
        echo "Access Key length: ${#AWS_ACCESS_KEY_ID}"
        echo "Secret Key length: ${#AWS_SECRET_ACCESS_KEY}"
      - echo "Building and testing Keycloak SPI module..."
      - ./gradlew :keycloak-spi:compileKotlin :keycloak-spi:test :keycloak-spi:shadowJar --no-daemon
      - echo "Build successful!"
