# Keycloak SPI - Deploy from GitHub Release
# Downloads the SPI JAR from GitHub Release and deploys to Keycloak.
# Build & release is handled by GitHub Actions (.github/workflows/keycloak-spi.yml).
#
# Trigger: woodpecker-cli pipeline create dsjkeeplearning/kos-auth-backend --branch main --var DEPLOY_TO=keycloak-spi
when:
  - event: manual
    evaluate: 'CI_PIPELINE_DEPLOY_TO == "keycloak-spi"'

steps:
  - name: download-release
    image: alpine
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - apk add --no-cache github-cli
      - |
        # Find latest spi-v* release
        LATEST_TAG=$(gh release list --repo ${CI_REPO} --limit 50 | grep 'spi-v' | head -1 | awk '{print $1}')
        if [ -z "$LATEST_TAG" ]; then
          echo "ERROR: No spi-v* release found"
          exit 1
        fi
        echo "Downloading JAR from release $LATEST_TAG"
        mkdir -p release-assets
        gh release download "$LATEST_TAG" --repo ${CI_REPO} --pattern "keycloak-user-storage-spi*.jar" --dir release-assets
        echo "Downloaded:" && ls -la release-assets/

  - name: deploy
    image: docker:cli
    volumes:
      - /opt/keycloak-providers:/shared/providers
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - mkdir -p /shared/providers
      - rm -f /shared/providers/*.jar
      - |
        SPI_JAR=$(ls release-assets/keycloak-user-storage-spi*.jar 2>/dev/null | head -1)
        if [ -z "$SPI_JAR" ]; then
          echo "ERROR: No SPI JAR found in release-assets/"
          exit 1
        fi
        cp "$SPI_JAR" /shared/providers/keycloak-user-storage-spi.jar
        echo "Deployed to /opt/keycloak-providers/"
        echo "Restarting Keycloak to load new SPI..."
        docker restart keycloak || echo "Warning - Could not restart keycloak container"
        echo "Deploy complete!"
