# Keycloak SPI - Build & Test (Push/PR/Manual)
# Manual trigger: woodpecker-cli pipeline create dsjkeeplearning/kos-auth-backend --branch main --var DEPLOY_TO=keycloak-spi-build
when:
  - event: pull_request
    path:
      include:
        - "keycloak-spi/**"
        - "settings.gradle.kts"
        - ".woodpecker/keycloak-spi.yml"
  - event: push
    branch: main
    path:
      include:
        - "keycloak-spi/**"
        - "settings.gradle.kts"
        - ".woodpecker/keycloak-spi.yml"
  - event: manual
    evaluate: 'CI_PIPELINE_DEPLOY_TO == "keycloak-spi-build"'

steps:
  - name: build-and-test
    image: amazoncorretto:21
    volumes:
      - /var/lib/woodpecker/cache/gradle:/root/.gradle
    environment:
      CI: "true"
      S3_BUILD_CACHE_BUCKET:
        from_secret: s3_build_cache_bucket
      S3_BUILD_CACHE_REGION:
        from_secret: s3_build_cache_region
      AWS_ACCESS_KEY_ID:
        from_secret: s3_build_cache_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: s3_build_cache_secret_key
      S3_BUILD_CACHE_ENDPOINT:
        from_secret: s3_build_cache_endpoint
    commands:
      - rm -rf /root/.gradle/daemon 2>/dev/null || true
      - find /root/.gradle -name "*.lock" -type f -delete 2>/dev/null || true
      - ./gradlew :keycloak-spi:compileKotlin :keycloak-spi:test :keycloak-spi:shadowJar --no-daemon
