when:
  - event: tag

steps:
  - name: build
    image: eclipse-temurin:21-jdk
    commands:
      - export VERSION=${CI_COMMIT_TAG#v}
      - ./gradlew :keycloak-spi:shadowJar -Pversion=$VERSION --no-daemon
      - mkdir -p /shared/providers
      - rm -f /shared/providers/keycloak-user-storage-spi*.jar
      - cp keycloak-spi/build/libs/keycloak-user-storage-spi-*.jar /shared/providers/keycloak-user-storage-spi.jar
    volumes:
      - /opt/keycloak-providers:/shared/providers

  - name: github-release
    image: woodpeckerci/plugin-release
    settings:
      files:
        - keycloak-spi/build/libs/keycloak-user-storage-spi-*.jar
      title: ${CI_COMMIT_TAG}
      note: "Keycloak User Storage SPI Release ${CI_COMMIT_TAG}"
      api_key:
        from_secret: github_token
