# Combined Release (Tag: release-v* or Manual)
# Use this to release both modules together
when:
  - event: tag
    ref: refs/tags/release-v*
  - event: manual

steps:
  - name: determine-version
    image: alpine/git
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - |
        if [ "$CI_PIPELINE_EVENT" = "manual" ]; then
          # Auto-increment: find latest release-v* tag and bump patch version
          LATEST_TAG=$(git tag -l 'release-v*' --sort=-v:refname | head -n1)
          if [ -z "$LATEST_TAG" ]; then
            NEW_VERSION="release-v1.0.0"
          else
            # Extract version numbers
            VERSION=${LATEST_TAG#release-v}
            MAJOR=$(echo $VERSION | cut -d. -f1)
            MINOR=$(echo $VERSION | cut -d. -f2)
            PATCH=$(echo $VERSION | cut -d. -f3)
            # Increment patch
            PATCH=$((PATCH + 1))
            NEW_VERSION="release-v$MAJOR.$MINOR.$PATCH"
          fi
          echo "Auto-incrementing to $NEW_VERSION"

          # Create and push tag
          git config --global user.email "ci@keeplearningos.com"
          git config --global user.name "Woodpecker CI"
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/${CI_REPO}.git
          git tag $NEW_VERSION
          git push origin $NEW_VERSION

          echo $NEW_VERSION > .version
        else
          echo $CI_COMMIT_TAG > .version
        fi
        echo "Version: $(cat .version)"

  - name: build-all
    image: eclipse-temurin:21-jdk
    environment:
      GRADLE_USER_HOME: /root/.gradle
      CI: "true"
      S3_BUILD_CACHE_BUCKET:
        from_secret: s3_build_cache_bucket
      S3_BUILD_CACHE_REGION:
        from_secret: s3_build_cache_region
      S3_BUILD_CACHE_ACCESS_KEY_ID:
        from_secret: s3_build_cache_access_key_id
      S3_BUILD_CACHE_SECRET_KEY:
        from_secret: s3_build_cache_secret_key
      S3_BUILD_CACHE_ENDPOINT:
        from_secret: s3_build_cache_endpoint
    commands:
      - VERSION=$(cat .version)
      - VERSION=${VERSION#release-v}
      - echo "Building all modules version $VERSION"
      - ./gradlew :keycloak-spi:shadowJar bootJar -Pversion=$VERSION --no-daemon  -x test
      - mkdir -p release-assets
      - cp keycloak-spi/build/libs/keycloak-user-storage-spi-*.jar release-assets/
      - cp build/libs/*.jar release-assets/
    volumes:
      - /opt/woodpecker-cache/gradle:/root/.gradle

  - name: generate-changelog
    image: alpine/git
    commands:
      - |
        VERSION=$(cat .version)
        PREV_TAG=$(git tag -l 'release-v*' --sort=-v:refname | grep -v $VERSION | head -n1)
        if [ -z "$PREV_TAG" ]; then
          PREV_TAG=$(git rev-list --max-parents=0 HEAD)
        fi
        echo "Generating changelog from $PREV_TAG to $VERSION"

        echo "# Changelog for $VERSION" > release-assets/CHANGELOG.md
        echo "" >> release-assets/CHANGELOG.md

        echo "## Auth Backend Changes" >> release-assets/CHANGELOG.md
        git log $PREV_TAG..HEAD --pretty=format:"- %s (%h)" -- src/ build.gradle.kts >> release-assets/CHANGELOG.md || echo "- No changes" >> release-assets/CHANGELOG.md
        echo "" >> release-assets/CHANGELOG.md
        echo "" >> release-assets/CHANGELOG.md

        echo "## Keycloak SPI Changes" >> release-assets/CHANGELOG.md
        git log $PREV_TAG..HEAD --pretty=format:"- %s (%h)" -- keycloak-spi/ >> release-assets/CHANGELOG.md || echo "- No changes" >> release-assets/CHANGELOG.md
        echo "" >> release-assets/CHANGELOG.md
        echo "" >> release-assets/CHANGELOG.md

        echo "## Other Changes" >> release-assets/CHANGELOG.md
        git log $PREV_TAG..HEAD --pretty=format:"- %s (%h)" -- . ':!keycloak-spi/' ':!src/' >> release-assets/CHANGELOG.md || echo "- No changes" >> release-assets/CHANGELOG.md
        echo "" >> release-assets/CHANGELOG.md

        cat release-assets/CHANGELOG.md

  - name: deploy-spi
    image: alpine
    commands:
      - mkdir -p /shared/providers
      - rm -f /shared/providers/keycloak-user-storage-spi*.jar
      - cp release-assets/keycloak-user-storage-spi-*.jar /shared/providers/keycloak-user-storage-spi.jar
      - echo "Deployed SPI to /opt/keycloak-providers/"
    volumes:
      - /opt/keycloak-providers:/shared/providers

  - name: update-readme
    image: alpine/git
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - VERSION=$(cat .version)
      - SEMVER=$(echo ${VERSION} | sed 's/^release-//')
      - git config --global user.email "ci@keeplearningos.com"
      - git config --global user.name "Woodpecker CI"
      - git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/${CI_REPO}.git
      - git fetch origin main
      - git checkout main
      - sed -i "s|auth-v[0-9.]*-blue|auth-${SEMVER}-blue|g" README.md
      - sed -i "s|keycloak--spi-v[0-9.]*-green|keycloak--spi-${SEMVER}-green|g" README.md
      - git add README.md
      - git diff --cached --quiet || git commit -m "Update version badges to ${VERSION}"
      - git push origin main

  - name: github-release
    image: alpine
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - apk add --no-cache github-cli
      - VERSION=$(cat .version)
      - |
        if gh release view $VERSION --repo $CI_REPO > /dev/null 2>&1; then
          echo "Release $VERSION already exists, uploading assets..."
          gh release upload $VERSION --repo $CI_REPO --clobber release-assets/*.jar
        else
          gh release create $VERSION \
            --repo $CI_REPO \
            --title "Release $VERSION" \
            --notes-file release-assets/CHANGELOG.md \
            release-assets/*.jar
        fi
