# Combined Release (Tag: release-v*)
# Use this to release both modules together
when:
  - event: tag
    ref: refs/tags/release-v*

steps:
  - name: build-all
    image: eclipse-temurin:21-jdk
    commands:
      - export VERSION=${CI_COMMIT_TAG#release-v}
      - echo "Building all modules version $VERSION"
      - ./gradlew :keycloak-spi:shadowJar bootJar -Pversion=$VERSION --no-daemon --build-cache -x test
      - mkdir -p release-assets
      - cp keycloak-spi/build/libs/keycloak-user-storage-spi-*.jar release-assets/
      - cp build/libs/*.jar release-assets/
    volumes:
      - /opt/woodpecker-cache/gradle:/root/.gradle

  - name: generate-changelog
    image: alpine/git
    commands:
      - |
        PREV_TAG=$(git tag -l 'release-v*' --sort=-v:refname | grep -v ${CI_COMMIT_TAG} | head -n1)
        if [ -z "$PREV_TAG" ]; then
          PREV_TAG=$(git rev-list --max-parents=0 HEAD)
        fi
        echo "Generating changelog from $PREV_TAG to ${CI_COMMIT_TAG}"

        echo "# Changelog for ${CI_COMMIT_TAG}" > release-assets/CHANGELOG.md
        echo "" >> release-assets/CHANGELOG.md

        echo "## Auth Backend Changes" >> release-assets/CHANGELOG.md
        git log $PREV_TAG..HEAD --pretty=format:"- %s (%h)" -- src/ build.gradle.kts >> release-assets/CHANGELOG.md || echo "- No changes" >> release-assets/CHANGELOG.md
        echo "" >> release-assets/CHANGELOG.md
        echo "" >> release-assets/CHANGELOG.md

        echo "## Keycloak SPI Changes" >> release-assets/CHANGELOG.md
        git log $PREV_TAG..HEAD --pretty=format:"- %s (%h)" -- keycloak-spi/ >> release-assets/CHANGELOG.md || echo "- No changes" >> release-assets/CHANGELOG.md
        echo "" >> release-assets/CHANGELOG.md
        echo "" >> release-assets/CHANGELOG.md

        echo "## Other Changes" >> release-assets/CHANGELOG.md
        git log $PREV_TAG..HEAD --pretty=format:"- %s (%h)" -- . ':!keycloak-spi/' ':!src/' >> release-assets/CHANGELOG.md || echo "- No changes" >> release-assets/CHANGELOG.md
        echo "" >> release-assets/CHANGELOG.md

        cat release-assets/CHANGELOG.md

  - name: deploy-spi
    image: alpine
    commands:
      - mkdir -p /shared/providers
      - rm -f /shared/providers/keycloak-user-storage-spi*.jar
      - cp release-assets/keycloak-user-storage-spi-*.jar /shared/providers/keycloak-user-storage-spi.jar
      - echo "Deployed SPI to /opt/keycloak-providers/"
    volumes:
      - /opt/keycloak-providers:/shared/providers

  - name: update-readme
    image: alpine/git
    environment:
      GIT_TERMINAL_PROMPT: "0"
    commands:
      - git config --global user.email "ci@keeplearningos.com"
      - git config --global user.name "Woodpecker CI"
      - git fetch origin main
      - git checkout main
      - sed -i "s|auth-v[0-9.]*-|auth-${CI_COMMIT_TAG}-|g" README.md
      - sed -i "s|keycloak--spi-spi--v[0-9.]*-|keycloak--spi-${CI_COMMIT_TAG}-|g" README.md
      - git add README.md
      - git diff --cached --quiet || git commit -m "Update version badges to ${CI_COMMIT_TAG}"
      - git push origin main

  - name: github-release
    image: woodpeckerci/plugin-release
    settings:
      files:
        - release-assets/*
      title: "Release ${CI_COMMIT_TAG}"
      note: release-assets/CHANGELOG.md
      api_key:
        from_secret: github_token
