/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "include" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type { RouteRecordRaw } from 'vue-router'

  export const routes: RouteRecordRaw[]
}
